<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 7 Machine Learning (en una aplicación urbana) | Analítica Urbana</title>
  <meta name="description" content="Un manual para la obtención, procesamiento, análisis y visualización de datos urbanos" />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 7 Machine Learning (en una aplicación urbana) | Analítica Urbana" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Un manual para la obtención, procesamiento, análisis y visualización de datos urbanos" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 7 Machine Learning (en una aplicación urbana) | Analítica Urbana" />
  
  <meta name="twitter:description" content="Un manual para la obtención, procesamiento, análisis y visualización de datos urbanos" />
  

<meta name="author" content="Antonio Vazquez Brust &amp; Angie Scetta" />


<meta name="date" content="2020-04-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analizando-movimiento-el-flujo-de-viajes-urbanos.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.3/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.3/leaflet-providers-plugin.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Analítica Urbana</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>¿Para quién es esto?</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#antes-de-empezar"><i class="fa fa-check"></i>Antes de empezar</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#sobre-la-analítica-urbana"><i class="fa fa-check"></i><b>1.1</b> Sobre la analítica urbana</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html"><i class="fa fa-check"></i><b>2</b> Geoprocesamiento</a><ul>
<li class="chapter" data-level="2.1" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#cruces-espaciales"><i class="fa fa-check"></i><b>2.1</b> Cruces espaciales</a></li>
<li class="chapter" data-level="2.2" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#dataframes-tradicionales-y-dataframes-espaciales"><i class="fa fa-check"></i><b>2.2</b> Dataframes tradicionales y dataframes espaciales</a><ul>
<li class="chapter" data-level="2.2.1" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#combinando-datasets-con-información-espacial"><i class="fa fa-check"></i><b>2.2.1</b> Combinando datasets con información espacial</a></li>
<li class="chapter" data-level="2.2.2" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#coropletas"><i class="fa fa-check"></i><b>2.2.2</b> Coropletas</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#uniones"><i class="fa fa-check"></i><b>2.3</b> Uniones</a></li>
<li class="chapter" data-level="2.4" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#intersecciones"><i class="fa fa-check"></i><b>2.4</b> Intersecciones</a></li>
<li class="chapter" data-level="2.5" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#distancias"><i class="fa fa-check"></i><b>2.5</b> Distancias</a></li>
<li class="chapter" data-level="2.6" data-path="geoprocesamiento.html"><a href="geoprocesamiento.html#cálculo-de-extensión-longitud-área"><i class="fa fa-check"></i><b>2.6</b> Cálculo de extensión (longitud, área)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><i class="fa fa-check"></i><b>3</b> Acceso a información urbana georeferenciada en repositorios <em>online</em></a><ul>
<li class="chapter" data-level="3.1" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html#openstreetmap-desde-r"><i class="fa fa-check"></i><b>3.1</b> OpenStreetMap desde R</a><ul>
<li class="chapter" data-level="3.1.1" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html#definiendo-el-lugar"><i class="fa fa-check"></i><b>3.1.1</b> Definiendo el lugar</a></li>
<li class="chapter" data-level="3.1.2" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html#extrayendo-información-de-openstreetmap"><i class="fa fa-check"></i><b>3.1.2</b> Extrayendo información de OpenStreetMap</a></li>
<li class="chapter" data-level="3.1.3" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html#visualizando-los-resultados"><i class="fa fa-check"></i><b>3.1.3</b> Visualizando los resultados</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html"><a href="acceso-a-información-urbana-georeferenciada-en-repositorios-online.html#un-ejercicio-más-bares-en-el-barrio"><i class="fa fa-check"></i><b>3.2</b> Un ejercicio más: ¡Bares en el barrio!</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html"><i class="fa fa-check"></i><b>4</b> Obteniendo y analizando datos de redes sociales</a><ul>
<li class="chapter" data-level="4.1" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#investigando-con-social-media"><i class="fa fa-check"></i><b>4.1</b> Investigando con social media</a><ul>
<li class="chapter" data-level="4.1.1" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#los-desafíos-de-trabajar-con-información-de-repositorios-sociales"><i class="fa fa-check"></i><b>4.1.1</b> Los desafíos de trabajar con información de repositorios sociales</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#conectando-r-a-twitter"><i class="fa fa-check"></i><b>4.2</b> Conectando R a Twitter</a><ul>
<li class="chapter" data-level="4.2.1" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#obteniendo-autorización"><i class="fa fa-check"></i><b>4.2.1</b> Obteniendo autorización</a></li>
<li class="chapter" data-level="4.2.2" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#acceso-a-twitter-via-r-el-paquete-rtweet"><i class="fa fa-check"></i><b>4.2.2</b> Acceso a Twitter via R: el paquete <em>rtweet</em></a></li>
<li class="chapter" data-level="4.2.3" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#usuarios-más-populares"><i class="fa fa-check"></i><b>4.2.3</b> Usuarios más populares</a></li>
<li class="chapter" data-level="4.2.4" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#tweets-más-populares"><i class="fa fa-check"></i><b>4.2.4</b> Tweets más populares</a></li>
<li class="chapter" data-level="4.2.5" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#la-hora-del-día-a-la-que-se-producen-los-tweets"><i class="fa fa-check"></i><b>4.2.5</b> La hora del día a la que se producen los tweets</a></li>
<li class="chapter" data-level="4.2.6" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#procedencia-de-los-usuarios"><i class="fa fa-check"></i><b>4.2.6</b> Procedencia de los usuarios</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#escuchando-tweets-en-tiempo-real"><i class="fa fa-check"></i><b>4.3</b> Escuchando tweets en tiempo real</a></li>
<li class="chapter" data-level="4.4" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#capturando-tweets-por-períodos-prolongados"><i class="fa fa-check"></i><b>4.4</b> Capturando tweets por períodos prolongados</a></li>
<li class="chapter" data-level="4.5" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#capturando-tweets-en-zonas-específicas"><i class="fa fa-check"></i><b>4.5</b> Capturando tweets en zonas específicas</a><ul>
<li class="chapter" data-level="4.5.1" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#extraer-las-coordenadas"><i class="fa fa-check"></i><b>4.5.1</b> Extraer las coordenadas</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#visualizando-los-datos-georeferenciados"><i class="fa fa-check"></i><b>4.6</b> Visualizando los datos georeferenciados</a><ul>
<li class="chapter" data-level="4.6.1" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#mapas-estáticos-con-ggmap"><i class="fa fa-check"></i><b>4.6.1</b> Mapas estáticos con ggmap</a></li>
<li class="chapter" data-level="4.6.2" data-path="obteniendo-y-analizando-datos-de-redes-sociales.html"><a href="obteniendo-y-analizando-datos-de-redes-sociales.html#mapas-interactivos-con-leaflet"><i class="fa fa-check"></i><b>4.6.2</b> Mapas interactivos con leaflet</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html"><i class="fa fa-check"></i><b>5</b> Analizando dinámicas espacio-temporales</a><ul>
<li class="chapter" data-level="5.0.1" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#trabajando-con-fechas"><i class="fa fa-check"></i><b>5.0.1</b> Trabajando con fechas</a></li>
<li class="chapter" data-level="5.1" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#mirando-al-espacio"><i class="fa fa-check"></i><b>5.1</b> Mirando al espacio</a><ul>
<li class="chapter" data-level="5.1.1" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#obteniendo-un-mapa-base"><i class="fa fa-check"></i><b>5.1.1</b> Obteniendo un mapa base</a></li>
<li class="chapter" data-level="5.1.2" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#de-coordenadas-al-mapa"><i class="fa fa-check"></i><b>5.1.2</b> De coordenadas al mapa</a></li>
<li class="chapter" data-level="5.1.3" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#mapas-de-densidad"><i class="fa fa-check"></i><b>5.1.3</b> Mapas de densidad</a></li>
<li class="chapter" data-level="5.1.4" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#visualizando-multiples-categorías"><i class="fa fa-check"></i><b>5.1.4</b> Visualizando multiples categorías</a></li>
<li class="chapter" data-level="5.1.5" data-path="analizando-dinámicas-espacio-temporales.html"><a href="analizando-dinámicas-espacio-temporales.html#combinando-espacio-y-tiempo"><i class="fa fa-check"></i><b>5.1.5</b> Combinando espacio y tiempo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><i class="fa fa-check"></i><b>6</b> Analizando movimiento: el flujo de viajes urbanos</a><ul>
<li class="chapter" data-level="6.1" data-path="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html#estimando-rutas"><i class="fa fa-check"></i><b>6.1</b> Estimando rutas</a></li>
<li class="chapter" data-level="6.2" data-path="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html#cuantificando-interacción"><i class="fa fa-check"></i><b>6.2</b> Cuantificando interacción</a></li>
<li class="chapter" data-level="6.3" data-path="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html#estimando-rutas-1"><i class="fa fa-check"></i><b>6.3</b> Estimando rutas</a></li>
<li class="chapter" data-level="6.4" data-path="analizando-movimiento-el-flujo-de-viajes-urbanos.html"><a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html#extra-cómo-obtener-las-rutas-de-todos-los-recorridos"><i class="fa fa-check"></i><b>6.4</b> EXTRA: Cómo obtener las rutas de todos los recorridos</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html"><i class="fa fa-check"></i><b>7</b> Machine Learning (en una aplicación urbana)</a><ul>
<li class="chapter" data-level="7.1" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-0-cargar-paquetes"><i class="fa fa-check"></i><b>7.1</b> Paso 0: Cargar paquetes</a></li>
<li class="chapter" data-level="7.2" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-1-cargar-los-datos"><i class="fa fa-check"></i><b>7.2</b> Paso 1: Cargar los datos</a></li>
<li class="chapter" data-level="7.3" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-2-examinar-los-datos"><i class="fa fa-check"></i><b>7.3</b> Paso 2: Examinar los datos</a></li>
<li class="chapter" data-level="7.4" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-3-limpiar-los-datos"><i class="fa fa-check"></i><b>7.4</b> Paso 3: Limpiar los datos</a><ul>
<li class="chapter" data-level="7.4.1" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#imputar-valores-faltantes"><i class="fa fa-check"></i><b>7.4.1</b> Imputar valores faltantes</a></li>
<li class="chapter" data-level="7.4.2" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#codificar-variables-categóricas"><i class="fa fa-check"></i><b>7.4.2</b> Codificar variables categóricas</a></li>
<li class="chapter" data-level="7.4.3" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#unificar-la-escala-de-las-variables-numéricas"><i class="fa fa-check"></i><b>7.4.3</b> Unificar la escala de las variables numéricas</a></li>
<li class="chapter" data-level="7.4.4" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#consolidar-todas-las-variables-generadas-ad-hoc-en-un-sólo-dataframe"><i class="fa fa-check"></i><b>7.4.4</b> Consolidar todas las variables generadas ad-hoc en un sólo dataframe</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-4-crear-sets-de-entrenamiento-y-de-testeo"><i class="fa fa-check"></i><b>7.5</b> Paso 4: Crear sets de entrenamiento y de testeo</a><ul>
<li class="chapter" data-level="7.5.1" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#paso-5-entrenar-y-testear-un-modelo"><i class="fa fa-check"></i><b>7.5.1</b> Paso 5: Entrenar y testear un modelo</a></li>
<li class="chapter" data-level="7.5.2" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#midiendo-la-performance-del-modelo-contra-datos-que-no-conoce"><i class="fa fa-check"></i><b>7.5.2</b> Midiendo la performance del modelo contra datos que no conoce</a></li>
<li class="chapter" data-level="7.5.3" data-path="machine-learning-en-una-aplicación-urbana.html"><a href="machine-learning-en-una-aplicación-urbana.html#comparando-performance"><i class="fa fa-check"></i><b>7.5.3</b> Comparando performance</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analítica Urbana</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="machine-learning-en-una-aplicación-urbana" class="section level1">
<h1><span class="header-section-number">Capítulo 7</span> Machine Learning (en una aplicación urbana)</h1>
<p>El así llamado <em>machine learning</em> consiste el empleo de aprendizaje estadístico automatizado para identificar patrones en grandes volúmenes de datos. El machine learning (de aquí en más ML) es utilizado en infinidad de campos debido a su creciente facilidad de uso y capacidad -en ciertos contextos- para predecir resultados con alta precisión.</p>
<p>A continuación veremos como se aplica ML para predecir el valor de venta de los departamentos en CABA a partir de un dataset publicado en el portal de datos abiertos <a href="https://data.buenosaires.gob.ar/">BA Data</a> que contiene el relevamiento de departamentos en venta que realizó el GCBA en 2016.</p>
<p>El objetivo del ejercicio es predecir el valor del metro cuadrado (USD x m2) de los departamentos en función de atributos como la cantidad de m2 descubiertos, la cantidad de ambientes, el barrio donde se ubican, la antiguedad de la construcción, etc.</p>
<p>Allá vamos.</p>
<div id="paso-0-cargar-paquetes" class="section level2">
<h2><span class="header-section-number">7.1</span> Paso 0: Cargar paquetes</h2>
<p>Además de las funciones de R “base”, vamos a usar las del paquete <code>tidyverse</code> para procesar y visualizar nuestros datos, las de <code>sf</code> para hacer algunos análisis espaciales y las de <code>randomForest</code>, para aplicar el algoritmo de ML homónimo, que es relativamente simple y a la vez efectivo.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb203-2" data-line-number="2"><span class="kw">library</span>(sf)</a>
<a class="sourceLine" id="cb203-3" data-line-number="3"><span class="co">#install.packages(&quot;randomForest&quot;)</span></a>
<a class="sourceLine" id="cb203-4" data-line-number="4"><span class="kw">library</span>(randomForest)</a></code></pre></div>
</div>
<div id="paso-1-cargar-los-datos" class="section level2">
<h2><span class="header-section-number">7.2</span> Paso 1: Cargar los datos</h2>
<p>Descargamos de BA Data el dataset del relevamiento de departamentos en venta del siguiente modo:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://cdn.buenosaires.gob.ar/datosabiertos/datasets/departamentos-en-venta/departamentos-en-venta-2016.csv&quot;</span>,</a>
<a class="sourceLine" id="cb204-2" data-line-number="2">                       <span class="dt">encoding=</span><span class="st">&quot;UTF-8&quot;</span>,</a>
<a class="sourceLine" id="cb204-3" data-line-number="3">                       <span class="dt">sep=</span><span class="st">&quot;;&quot;</span>)</a></code></pre></div>
</div>
<div id="paso-2-examinar-los-datos" class="section level2">
<h2><span class="header-section-number">7.3</span> Paso 2: Examinar los datos</h2>
<p>Echamos un vistazo a los nombres de las columnas y las primeras filas del dataset:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1"><span class="kw">names</span>(dptos_<span class="dv">2016</span>)</a></code></pre></div>
<pre><code>##  [1] &quot;CALLE&quot;                   &quot;NUMERO&quot;                 
##  [3] &quot;ID_ZONAPRO&quot;              &quot;OPERACION&quot;              
##  [5] &quot;TIPO&quot;                    &quot;M2&quot;                     
##  [7] &quot;M2CUB&quot;                   &quot;PRECIOTEXT&quot;             
##  [9] &quot;PRECIOARS&quot;               &quot;PRECIOARSM&quot;             
## [11] &quot;DOLARES&quot;                 &quot;U_S_M2&quot;                 
## [13] &quot;AMBIENTES&quot;               &quot;ANTIGUEDAD&quot;             
## [15] &quot;BAÑOS&quot;                   &quot;DIRECCION&quot;              
## [17] &quot;LOCATION&quot;                &quot;PUBLICADO&quot;              
## [19] &quot;PROCESADO&quot;               &quot;URL&quot;                    
## [21] &quot;REVISION&quot;                &quot;NOTA&quot;                   
## [23] &quot;DIRECCION_NORMALIZADA&quot;   &quot;BARRIO&quot;                 
## [25] &quot;COMUNA&quot;                  &quot;CODIGO_POSTAL&quot;          
## [27] &quot;CODIGO_POSTAL_ARGENTINO&quot; &quot;LATITUD&quot;                
## [29] &quot;LONGITUD&quot;</code></pre>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">head</span>(dptos_<span class="dv">2016</span>)</a></code></pre></div>
<pre><code>##                CALLE NUMERO ID_ZONAPRO OPERACION TIPO  M2 M2CUB  PRECIOTEXT
## 1          GUATEMALA   5574   42408691       VTA  DTO  57    50 U$S 170.150
## 2             ZAPATA    300   42408710       VTA  DTO  46    46 U$S 118.650
## 3             ZAPATA    300   42518390       VTA  DTO  61    56 U$S 181.470
## 4             ZAPATA    300   42518402       VTA  DTO 140    76 U$S 320.000
## 5 JUSTO, JUAN B. AV.   2300   42621693       VTA  DTO  39    33  U$S 82.116
## 6 JUSTO, JUAN B. AV.   2300   42621702       VTA  DTO  39    34  U$S 81.921
##   PRECIOARS PRECIOARSM DOLARES U_S_M2 AMBIENTES ANTIGUEDAD BAÑOS
## 1   2977625      59553  170150   3403         2       2016     1
## 2   2076375      45139  118650   2579         0       2016     1
## 3   3175725      56709  181470   3241         2       2016     1
## 4   5600000      73684  320000   4211         2       2016     1
## 5   1437030      43546   82116   2488         0       2016     1
## 6   1433617      42165   81921   2409         0       2016     1
##                      DIRECCION
## 1               GUATEMALA 5574
## 2                   ZAPATA 300
## 3                   ZAPATA 300
## 4                   ZAPATA 300
## 5 JUSTO  JUAN B. AVDA. AL 2300
## 6 JUSTO  JUAN B. AVDA. AL 2300
##                                                      LOCATION  PUBLICADO
## 1                  GUATEMALA 5574  PALERMO HOLLYWOOD  PALERMO 27/11/2016
## 2                       ZAPATA 300  BELGRANO  CAPITAL FEDERAL 27/11/2016
## 3                       ZAPATA 300  BELGRANO  CAPITAL FEDERAL 27/11/2016
## 4                       ZAPATA 300  BELGRANO  CAPITAL FEDERAL 27/11/2016
## 5 JUSTO  JUAN B. AVDA. AL 2300  VILLA CRESPO  CAPITAL FEDERAL  27/7/2016
## 6 JUSTO  JUAN B. AVDA. AL 2300  VILLA CRESPO  CAPITAL FEDERAL  27/7/2016
##    PROCESADO                                                    URL REVISION
## 1 12/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42408691.HTML       NA
## 2 12/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42408710.HTML       NA
## 3 11/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42518390.HTML       NA
## 4 11/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42518402.HTML       NA
## 5 10/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42621693.HTML       NA
## 6 10/10/2017 HTTP://WWW.ZONAPROP.COM.AR/PROPIEDADES/A-42621702.HTML       NA
##   NOTA   DIRECCION_NORMALIZADA       BARRIO    COMUNA CODIGO_POSTAL
## 1   NA          GUATEMALA 5574      PALERMO COMUNA 14          1425
## 2   NA              ZAPATA 300      PALERMO COMUNA 14          1426
## 3   NA              ZAPATA 300      PALERMO COMUNA 14          1426
## 4   NA              ZAPATA 300      PALERMO COMUNA 14          1426
## 5   NA JUSTO, JUAN B. AV. 2300 VILLA CRESPO COMUNA 15          1414
## 6   NA JUSTO, JUAN B. AV. 2300 VILLA CRESPO COMUNA 15          1414
##   CODIGO_POSTAL_ARGENTINO   LATITUD  LONGITUD
## 1                C1425BVH -34.58058 -58.43176
## 2                C1426AED -34.57387 -58.44061
## 3                C1426AED -34.57387 -58.44061
## 4                C1426AED -34.57387 -58.44061
## 5                C1414CWY -34.59298 -58.44154
## 6                C1414CWY -34.59298 -58.44154</code></pre>
<p>El dataset contiene 29 columnas (mucha información!). Por lo tanto, debemos revisar las variables y hacer una preselección para incluir solo aquellas que consideremos relevantes para nuestro modelo:</p>
<ul>
<li>La variable a predecir (dependiente) será el valor del m2 de los departamentos (U_S_M2) en CABA.</li>
<li>Las variables predictoras (independientes) serán: cantidad de ambientes (AMBIENTES), años de antiguedad de la construcción (ANTIGUEDAD), cantidad de baños (BAÑOS), superficie total (M2), superficie cubierta (M2CUB), barrio al que pertenece (BARRIO) y coordenadas (LATITUD, LONGITUD).</li>
</ul>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb209-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>CALLE, <span class="op">-</span>NUMERO, <span class="op">-</span>ID_ZONAPRO, <span class="op">-</span>OPERACION, <span class="op">-</span>TIPO, <span class="op">-</span>PRECIOTEXT, <span class="op">-</span>PRECIOARS, <span class="op">-</span>PRECIOARSM, <span class="op">-</span>DOLARES, <span class="op">-</span>DIRECCION, <span class="op">-</span>LOCATION, <span class="op">-</span>PUBLICADO, <span class="op">-</span>PROCESADO, <span class="op">-</span>URL, <span class="op">-</span>REVISION, <span class="op">-</span>NOTA, <span class="op">-</span>DIRECCION_NORMALIZADA, <span class="op">-</span>COMUNA, <span class="op">-</span>CODIGO_POSTAL, <span class="op">-</span>CODIGO_POSTAL_ARGENTINO)</a></code></pre></div>
<p>Ahora veamos un resumen del contenido:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" data-line-number="1"><span class="kw">summary</span>(dptos_<span class="dv">2016</span>)</a></code></pre></div>
<pre><code>##        M2             M2CUB            U_S_M2        AMBIENTES     
##  Min.   : 15.00   Min.   :  0.00   Min.   :    0   Min.   : 0.000  
##  1st Qu.: 41.00   1st Qu.: 37.00   1st Qu.: 2242   1st Qu.: 2.000  
##  Median : 54.00   Median : 47.00   Median : 2651   Median : 2.000  
##  Mean   : 70.38   Mean   : 61.12   Mean   : 2804   Mean   : 2.456  
##  3rd Qu.: 80.00   3rd Qu.: 70.00   3rd Qu.: 3131   3rd Qu.: 3.000  
##  Max.   :730.00   Max.   :625.00   Max.   :12500   Max.   :10.000  
##                                                                    
##    ANTIGUEDAD         BAÑOS                BARRIO        LATITUD      
##  Min.   :   0.0   Min.   :0.00                :1382   Min.   :-34.68  
##  1st Qu.:   1.0   1st Qu.:1.00   CABALLITO    : 643   1st Qu.:-34.62  
##  Median :  30.0   Median :1.00   PALERMO      : 629   Median :-34.60  
##  Mean   : 710.6   Mean   :1.25   SAN CRISTOBAL: 563   Mean   :-34.60  
##  3rd Qu.:2016.0   3rd Qu.:2.00   VILLA CRESPO : 532   3rd Qu.:-34.58  
##  Max.   :2016.0   Max.   :6.00   BELGRANO     : 473   Max.   :-34.54  
##                                  (Other)      :3342   NA&#39;s   :1382    
##     LONGITUD     
##  Min.   :-58.53  
##  1st Qu.:-58.45  
##  Median :-58.43  
##  Mean   :-58.43  
##  3rd Qu.:-58.41  
##  Max.   :-58.35  
##  NA&#39;s   :1382</code></pre>
</div>
<div id="paso-3-limpiar-los-datos" class="section level2">
<h2><span class="header-section-number">7.4</span> Paso 3: Limpiar los datos</h2>
<div id="imputar-valores-faltantes" class="section level3">
<h3><span class="header-section-number">7.4.1</span> Imputar valores faltantes</h3>
<p>Es habitual que los algoritmos empleados para ML no acepten datos faltantes. Es por eso que la limpieza básica de un dataset casi siempre incluye la imputación de datos no disponibles, evitando descartar por incompletas filas que contienen información valiosa en sus campos si disponibles.</p>
<p>Hasta acá pudimos observar varias inconsistencias en los datos como por ejemplo:</p>
<ul>
<li>La variable M2CUB tiene valor 0 en algunos registros. Suponiendo que hubo un error en la carga de los datos, cuando M2CUB&lt;15 vamos a imputar el valor de M2, asumiendo que esa propiedad no tiene m2 descubiertos.</li>
<li>Hay casos donde M2CUB&gt;M2. Acá le imputaremos el valor del M2CUB al M2.</li>
<li>En la variable ANTIGUEDAD aparecen algunos registros con el valor 2016. Suponiendo que esas propiedades se construyeron en ese año, se imputará una antiguedad 0 ya que se fue en el mismo año del relevamiento.</li>
<li>Las variables AMBIENTES y BAÑOS tiene 0 en algunos registros. Imputaremos estos datos entendiendo que cuando AMBIENTES=0, es un monoambiente, y que cuando BAÑOS=0, es porque tienen 1 solo.</li>
<li>Hay 1382 valores faltantes en las columnas LONGITUD y LATITUD, y a su vez estos registros tampoco tienen comuna o barrio asignado, por lo tanto como nos va a resultar imposible ubicarlos en el espacio, debemos eliminarlos.</li>
<li>Por último, se puede ver que la variable a predecir (U_S_M2) varía entre 0 y 12500. Claramente ninguna propiedad puede tener un U_S_M2=0 o menos de 500 así que estos registros se filtrarán ya que son pocos casos.</li>
</ul>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb212-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">M2CUB=</span><span class="kw">ifelse</span>(M2CUB<span class="op">&lt;</span><span class="dv">15</span>, M2, M2CUB),</a>
<a class="sourceLine" id="cb212-3" data-line-number="3">         <span class="dt">M2=</span><span class="kw">ifelse</span>(M2CUB<span class="op">&gt;</span>M2, M2CUB, M2),</a>
<a class="sourceLine" id="cb212-4" data-line-number="4">         <span class="dt">ANTIGUEDAD=</span><span class="kw">ifelse</span>(ANTIGUEDAD<span class="op">==</span><span class="dv">2016</span>, <span class="dv">0</span>, ANTIGUEDAD),</a>
<a class="sourceLine" id="cb212-5" data-line-number="5">         BAÑ<span class="dt">OS =</span> <span class="kw">ifelse</span>(BAÑOS<span class="op">==</span><span class="dv">0</span>, <span class="dv">1</span>, BAÑOS),</a>
<a class="sourceLine" id="cb212-6" data-line-number="6">         <span class="dt">AMBIENTES =</span> <span class="kw">ifelse</span>(AMBIENTES<span class="op">==</span><span class="dv">0</span>, <span class="dv">1</span>, AMBIENTES)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb212-7" data-line-number="7"><span class="st">  </span><span class="kw">filter</span>(U_S_M2<span class="op">&gt;</span><span class="dv">500</span>,</a>
<a class="sourceLine" id="cb212-8" data-line-number="8">         <span class="op">!</span><span class="kw">is.na</span>(LATITUD), <span class="op">!</span><span class="kw">is.na</span>(LONGITUD))</a></code></pre></div>
<p>Ya tenemos preparadas las variables para nuestro modelo, pero aún estamos a tiempo de generar algunas nuevas que consideremos que lo mejorarían por tener capacidad predictiva sobre el valor del m2.
Por ejemplo, probemos calculando los metros descubiertos (M2DESC) de cada propiedad, ya que, es muy probable que tener alguna expansión (balcón o terraza) le de un valor agregado al departamento.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb213-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">M2DESC=</span>M2<span class="op">-</span>M2CUB)</a></code></pre></div>
<p>Ahora sí, volvamos a ver el resumen:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" data-line-number="1"><span class="kw">summary</span>(dptos_<span class="dv">2016</span>)</a></code></pre></div>
<pre><code>##        M2             M2CUB            U_S_M2        AMBIENTES     
##  Min.   : 15.00   Min.   : 15.00   Min.   :  608   Min.   : 1.000  
##  1st Qu.: 41.00   1st Qu.: 38.00   1st Qu.: 2230   1st Qu.: 2.000  
##  Median : 53.00   Median : 47.00   Median : 2631   Median : 2.000  
##  Mean   : 68.44   Mean   : 60.28   Mean   : 2768   Mean   : 2.518  
##  3rd Qu.: 78.00   3rd Qu.: 69.00   3rd Qu.: 3107   3rd Qu.: 3.000  
##  Max.   :730.00   Max.   :625.00   Max.   :10555   Max.   :10.000  
##                                                                    
##    ANTIGUEDAD          BAÑOS                 BARRIO        LATITUD      
##  Min.   :  0.000   Min.   :1.000   CABALLITO    : 643   Min.   :-34.68  
##  1st Qu.:  0.000   1st Qu.:1.000   PALERMO      : 629   1st Qu.:-34.62  
##  Median :  0.000   Median :1.000   SAN CRISTOBAL: 563   Median :-34.60  
##  Mean   :  8.896   Mean   :1.331   VILLA CRESPO : 532   Mean   :-34.60  
##  3rd Qu.: 10.000   3rd Qu.:2.000   BELGRANO     : 472   3rd Qu.:-34.58  
##  Max.   :110.000   Max.   :6.000   RECOLETA     : 406   Max.   :-34.54  
##                                    (Other)      :2933                   
##     LONGITUD          M2DESC       
##  Min.   :-58.53   Min.   :  0.000  
##  1st Qu.:-58.45   1st Qu.:  0.000  
##  Median :-58.43   Median :  4.000  
##  Mean   :-58.43   Mean   :  8.163  
##  3rd Qu.:-58.41   3rd Qu.:  8.000  
##  Max.   :-58.35   Max.   :282.000  
## </code></pre>
<p>Nos hemos librado de los <code>NA</code> y las inconsistencias que tenían los datos.</p>
<p>Y espiemos la distribución de algunas variables, como el valor del m2:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb216-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> U_S_M2))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-183-1.png" width="672" /></p>
<p>La superficie total:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb217-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> M2))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-184-1.png" width="672" /></p>
<p>La superficie descubierta:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb218-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> M2DESC))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-185-1.png" width="672" /></p>
<p>La antigüedad de las viviendas:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb219-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> ANTIGUEDAD))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-186-1.png" width="672" /></p>
<p>El Barrio (dado que se trata de una variable categórica en lugar de continua, usamos un gráfico de barras en lugar de un histograma):</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb220-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> BARRIO))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-187-1.png" width="672" /></p>
<p>Agreguemos una variable más: la distancia de los departamenteos a las estaciones de subte, ya que la cercanía a estas es muy probable que impacte en el valor del m2.
Acá utilizaremos uno de los geoprocesos que aprendimos algunos capítulos atrás: <code>st_distance</code></p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" data-line-number="1">subte_estaciones &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&quot;http://bitsandbricks.github.io/data/subte_estaciones.geojson&quot;</span>)</a></code></pre></div>
<pre><code>## Reading layer `subte_estaciones&#39; from data source `http://bitsandbricks.github.io/data/subte_estaciones.geojson&#39; using driver `GeoJSON&#39;
## Simple feature collection with 86 features and 3 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -58.48639 ymin: -34.64331 xmax: -58.36993 ymax: -34.55564
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<p>Transformemos dptos_2016 a un dataset espacial para poder medir distancias:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb223-2" data-line-number="2"><span class="st">    </span><span class="kw">st_as_sf</span>(<span class="dt">coords =</span> <span class="kw">c</span>(<span class="st">&quot;LONGITUD&quot;</span>, <span class="st">&quot;LATITUD&quot;</span>), <span class="dt">crs =</span> <span class="dv">4326</span>)</a></code></pre></div>
<p>Y ahora calculemos la distancia (en metros) entre cada departamento en venta y la estación de subte más cercana:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb224-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">DIST_SUBTE =</span> <span class="kw">apply</span>(<span class="kw">st_distance</span>(dptos_<span class="dv">2016</span>, subte_estaciones), <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="kw">min</span>(x)))</a></code></pre></div>
<p>Veamos un resumen de los resultados:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" data-line-number="1"><span class="kw">summary</span>(dptos_<span class="dv">2016</span><span class="op">$</span>DIST_SUBTE)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.35  282.77  477.19  706.81  762.33 5658.53</code></pre>
<p>El departamento ubicado a menor distancia de alguna estación de subte es a 1.35 metros y el que está a mayor distancia es a 5658 metros. Sin embargo, en promedio, las propiedades se ubican a 706 metros de alguna estación.</p>
<p>Nuestro dataset lo transformamos en espacial para medir distancias, pero como queremos utilizar LATITUD y LONGITUD para el modelo, debemos volver a separar las coordenadas y transformarlo en dataframe tradicional:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb227-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">LATITUD =</span> <span class="kw">unlist</span>(<span class="kw">map</span>(dptos_<span class="dv">2016</span><span class="op">$</span>geometry,<span class="dv">1</span>)),</a>
<a class="sourceLine" id="cb227-3" data-line-number="3">  <span class="dt">LONGITUD =</span> <span class="kw">unlist</span>(<span class="kw">map</span>(dptos_<span class="dv">2016</span><span class="op">$</span>geometry,<span class="dv">2</span>))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb227-4" data-line-number="4"><span class="st">  </span><span class="kw">st_set_geometry</span>(<span class="ot">NULL</span>)</a></code></pre></div>
</div>
<div id="codificar-variables-categóricas" class="section level3">
<h3><span class="header-section-number">7.4.2</span> Codificar variables categóricas</h3>
<p>Rara vez es posible utilizar columnas categóricas en modelos estadísticos, pero por suerte podemos recurrir a la alternativa de reemplazar una columna de datos categóricos por una serie de variables binarias, o “dummy”.
En nuestro dataset solo tenemos una variable categórica: BARRIO.</p>
<p>Entonces, en lugar de…</p>
<table>
<thead>
<tr class="header">
<th>dpto</th>
<th>BARRIO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>PALERMO</td>
</tr>
<tr class="even">
<td>B</td>
<td>BELGRANO</td>
</tr>
<tr class="odd">
<td>C</td>
<td>SAN TELMO</td>
</tr>
</tbody>
</table>
<p>… deberíamo tener algo así como:</p>
<table>
<thead>
<tr class="header">
<th>caso</th>
<th>PALERMO</th>
<th>BELGRANO</th>
<th>SAN TELMO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>B</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>C</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Como buen lenguaje creado por y para practicantes del análisis estadístico, <code>R</code> trae una función específica para realizar ésta tarea, <code>model.matrix()</code>. Se usa así:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb228-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">BARRIO=</span><span class="kw">str_replace_all</span>(BARRIO, <span class="st">&quot; &quot;</span>, <span class="st">&quot;_&quot;</span>))</a>
<a class="sourceLine" id="cb228-3" data-line-number="3">matriz_categorias_barrios &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="op">~</span><span class="st"> </span>BARRIO <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<p>y el resultado es, ni más ni menos, una matriz de variables binarias que representan las categorías originales:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" data-line-number="1"><span class="kw">head</span>(matriz_categorias_barrios)</a></code></pre></div>
<pre><code>##   BARRIOAGRONOMIA BARRIOALMAGRO BARRIOBALVANERA BARRIOBARRACAS BARRIOBELGRANO
## 1               0             0               0              0              0
## 2               0             0               0              0              0
## 3               0             0               0              0              0
## 4               0             0               0              0              0
## 5               0             0               0              0              0
## 6               0             0               0              0              0
##   BARRIOBOCA BARRIOBOEDO BARRIOCABALLITO BARRIOCHACARITA BARRIOCOGHLAN
## 1          0           0               0               0             0
## 2          0           0               0               0             0
## 3          0           0               0               0             0
## 4          0           0               0               0             0
## 5          0           0               0               0             0
## 6          0           0               0               0             0
##   BARRIOCOLEGIALES BARRIOCONSTITUCION BARRIOFLORES BARRIOFLORESTA BARRIOLINIERS
## 1                0                  0            0              0             0
## 2                0                  0            0              0             0
## 3                0                  0            0              0             0
## 4                0                  0            0              0             0
## 5                0                  0            0              0             0
## 6                0                  0            0              0             0
##   BARRIOMATADEROS BARRIOMONSERRAT BARRIOMONTE_CASTRO BARRIONUEVA_POMPEYA
## 1               0               0                  0                   0
## 2               0               0                  0                   0
## 3               0               0                  0                   0
## 4               0               0                  0                   0
## 5               0               0                  0                   0
## 6               0               0                  0                   0
##   BARRIONUÑEZ BARRIOPALERMO BARRIOPARQUE_AVELLANEDA BARRIOPARQUE_CHACABUCO
## 1           0             1                       0                      0
## 2           0             1                       0                      0
## 3           0             1                       0                      0
## 4           0             1                       0                      0
## 5           0             0                       0                      0
## 6           0             0                       0                      0
##   BARRIOPARQUE_CHAS BARRIOPARQUE_PATRICIOS BARRIOPATERNAL BARRIOPUERTO_MADERO
## 1                 0                      0              0                   0
## 2                 0                      0              0                   0
## 3                 0                      0              0                   0
## 4                 0                      0              0                   0
## 5                 0                      0              0                   0
## 6                 0                      0              0                   0
##   BARRIORECOLETA BARRIORETIRO BARRIOSAAVEDRA BARRIOSAN_CRISTOBAL
## 1              0            0              0                   0
## 2              0            0              0                   0
## 3              0            0              0                   0
## 4              0            0              0                   0
## 5              0            0              0                   0
## 6              0            0              0                   0
##   BARRIOSAN_NICOLAS BARRIOSAN_TELMO BARRIOVELEZ_SARSFIELD BARRIOVERSALLES
## 1                 0               0                     0               0
## 2                 0               0                     0               0
## 3                 0               0                     0               0
## 4                 0               0                     0               0
## 5                 0               0                     0               0
## 6                 0               0                     0               0
##   BARRIOVILLA_CRESPO BARRIOVILLA_DEL_PARQUE BARRIOVILLA_DEVOTO
## 1                  0                      0                  0
## 2                  0                      0                  0
## 3                  0                      0                  0
## 4                  0                      0                  0
## 5                  1                      0                  0
## 6                  1                      0                  0
##   BARRIOVILLA_GRAL._MITRE BARRIOVILLA_LUGANO BARRIOVILLA_LURO
## 1                       0                  0                0
## 2                       0                  0                0
## 3                       0                  0                0
## 4                       0                  0                0
## 5                       0                  0                0
## 6                       0                  0                0
##   BARRIOVILLA_ORTUZAR BARRIOVILLA_PUEYRREDON BARRIOVILLA_REAL
## 1                   0                      0                0
## 2                   0                      0                0
## 3                   0                      0                0
## 4                   0                      0                0
## 5                   0                      0                0
## 6                   0                      0                0
##   BARRIOVILLA_SANTA_RITA BARRIOVILLA_SOLDATI BARRIOVILLA_URQUIZA
## 1                      0                   0                   0
## 2                      0                   0                   0
## 3                      0                   0                   0
## 4                      0                   0                   0
## 5                      0                   0                   0
## 6                      0                   0                   0</code></pre>
<p>Pronto agregaremos la matriz a nuestro dataframe, pero antes terminemos con otros ajustes pendientes.</p>
</div>
<div id="unificar-la-escala-de-las-variables-numéricas" class="section level3">
<h3><span class="header-section-number">7.4.3</span> Unificar la escala de las variables numéricas</h3>
<p>Éste paso siempre es necesario cuando estamos trabajando con variables que utilizan distintas unidades de medida. Aquí tenemos superficies, ambientes, años de antigüedad… de todo. Muchos algoritmos asumen que todas las variables tienen escalas comparables, lo cual genera problemas con las que alcanzan los valores más altos (como m2, que a 730) versus las que tienen rangos mucho menores (como cantidad de baños, que llega a 6). Si las dejásemos así, varias de las técnicas habituales del ML adjudicarían mucho más peso a las variables con números grandes, “despreciando” a las que por su naturaleza se mueven en rango más reducidos.</p>
<p>En todo caso, no importa lo disimiles que sean las unidades de medida, la solución es simple: convertimos todas las variables a la famosa “distribución Z”, o función de estandarización, que convierte variables a una escala sin unidad de medida, que expresa cada valor como la cantidad de desvíos estándar que lo alejan de la media. Expresar todas las variables numéricas en forma de “z scores”, o “valores z”, las hace directamente comparables entre sí.</p>
<p>En <code>R</code> disponemos de la función <code>scale()</code>, que obtiene los z-scores. Tomaremos entonces nuestro dataframe y usaremos <code>mutate_all()</code> para aplicar una función a todas las columnas restantes de un tirón. Eso si, quitando antes ciertas variables: las variables categóricas (que no tiene sentido pasar a z-scores porque no son variables numéricas), y la variable que estamos intentando predecir, ya que su escala no afecta los modelos y podemos dejarla en su formato original fácil de interpretar.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" data-line-number="1">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb231-2" data-line-number="2"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>BARRIO) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb231-3" data-line-number="3"><span class="st">    </span><span class="kw">mutate_all</span>(<span class="kw">funs</span>(scale)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb231-4" data-line-number="4"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">U_S_M2 =</span> dptos_<span class="dv">2016</span><span class="op">$</span>U_S_M2)</a></code></pre></div>
<p>Y obsérvese que <code>scale()</code> mediante, ahora todas las variables tienen promedio igual a 0, y se mueven en el mismo rango</p>
<p>… y sin que esto haya cambiado la forma de las distribuciones. Compárense ahora con las que examinamos al inicio,</p>
<p>La superficie total:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb232-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> M2))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-196-1.png" width="672" /></p>
<p>La superficie descubierta:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb233-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> M2DESC))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-197-1.png" width="672" /></p>
<p>La antigüedad de las viviendas:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb234-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">data =</span> dptos_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> ANTIGUEDAD))</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-198-1.png" width="672" /></p>
<p>¡Las formas son iguales! no hemos hemos perdido “información” respecto a que tan típico o extremo es cada valor, y hemos ganado la posibilidad de comparar en forma directa todas las variables.</p>
</div>
<div id="consolidar-todas-las-variables-generadas-ad-hoc-en-un-sólo-dataframe" class="section level3">
<h3><span class="header-section-number">7.4.4</span> Consolidar todas las variables generadas ad-hoc en un sólo dataframe</h3>
<p>Nos ha quedado por un lado un dataframe de variables numéricas estandarizadas, y por otro una matriz que representa la pertenencia de cada departamento a un barrio de la Ciudad.</p>
<p>Primero convertimos la matriz en dataframe (paso simple ya éstas estructura de datos son muy similares entre si), y luego unimos las columnas de ambos con la función <code>cbind()</code>:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1">matriz_categorias_barrios &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(matriz_categorias_barrios)</a>
<a class="sourceLine" id="cb235-2" data-line-number="2"></a>
<a class="sourceLine" id="cb235-3" data-line-number="3">dptos_<span class="dv">2016</span> &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb235-4" data-line-number="4"><span class="st">    </span><span class="kw">cbind</span>(matriz_categorias_barrios)</a></code></pre></div>
<p>Ya tenemos tenemos los datos limpios y en orden.</p>
</div>
</div>
<div id="paso-4-crear-sets-de-entrenamiento-y-de-testeo" class="section level2">
<h2><span class="header-section-number">7.5</span> Paso 4: Crear sets de entrenamiento y de testeo</h2>
<p>Para poder evaluar la calidad de un modelo predictivo, es práctica común dividir los datos disponibles en dos porciones. Una parte será utilizada para “entrenar” el modelo de ML, es decir se le permitirá al algoritmo acceder a esos datos para establecer la forma en que cada variable predictora incide en la que se quiere predecir. El resto será preservado y utilizado para “tomarle examen” al modelo: se le mostraran sólo las variables predictoras de esos datos, pidiendo al modelo una predicción del valor a estimar para cada una. Por último, contrastando aciertos y errores, se podrá establecer el grado de precisión del modelo.</p>
<p>Incluso podríamos tener varios modelos distintos, obtenidos con distintas técnicas de ML. No es difícil, ya que una vez que los datos han sido obtenidos y preparados, nada impide usarlos como insumo de distintos algoritmos. En ese caso, se puede comparar la performance de los distintos modelos evaluando cual acierta mejor con la data de testeo.</p>
<p>Definamos entonces cuales filas van al set de entrenamiento, y cuáles al de testeo, eligiéndolas al azar. De acuerdo a distintas recetas, a veces se separa el 90% de los datos para entrenamiento y el resto para testeo, otras veces es mitad y mitad… ya que siempre es más o menos arbitrario, aquí usaremos el 80% para entrenar, y el 20% para testear.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1"><span class="co">#definimos a mano la &quot;semilla&quot; de aleatorización para obtener resultados reproducibles</span></a>
<a class="sourceLine" id="cb236-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">1111</span>)</a></code></pre></div>
<p>Tomamos al azar el 80% de las posiciones entre 1 y la cantidad total de filas de nuestro dataset:</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" data-line-number="1">seleccion &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(dptos_<span class="dv">2016</span>), <span class="dt">size =</span> <span class="kw">nrow</span>(dptos_<span class="dv">2016</span>) <span class="op">*</span><span class="st"> </span><span class="fl">0.8</span>)</a>
<a class="sourceLine" id="cb237-2" data-line-number="2"></a>
<a class="sourceLine" id="cb237-3" data-line-number="3">entrenamiento &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb237-4" data-line-number="4"><span class="st">    </span><span class="kw">filter</span>(<span class="kw">row_number</span>() <span class="op">%in%</span><span class="st"> </span>seleccion)</a>
<a class="sourceLine" id="cb237-5" data-line-number="5"></a>
<a class="sourceLine" id="cb237-6" data-line-number="6"><span class="co"># el testeo es el set opuesto - aquellas filas cuya posición no está entre las seleccionadas</span></a>
<a class="sourceLine" id="cb237-7" data-line-number="7"><span class="co"># el operador ! convierte una proposición en negativa </span></a>
<a class="sourceLine" id="cb237-8" data-line-number="8"></a>
<a class="sourceLine" id="cb237-9" data-line-number="9">testeo &lt;-<span class="st"> </span>dptos_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb237-10" data-line-number="10"><span class="st">    </span><span class="kw">filter</span>(<span class="op">!</span>(<span class="kw">row_number</span>() <span class="op">%in%</span><span class="st"> </span>seleccion))</a></code></pre></div>
<p>Ahora si, por fin, apliquemos un poco de machine learning.</p>
<div id="paso-5-entrenar-y-testear-un-modelo" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Paso 5: Entrenar y testear un modelo</h3>
<p>Random Forest, una implementación de árboles de decisión como los ilustrados en <a href="http://www.r2d3.us/una-introduccion-visual-al-machine-learning-1/">“Una introducción visual al machine learning”</a>:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">modelo_RF &lt;-<span class="st"> </span><span class="kw">randomForest</span>(<span class="dt">data =</span> entrenamiento, U_S_M2 <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb238-2" data-line-number="2">                         <span class="dt">ntree =</span> <span class="dv">500</span>,</a>
<a class="sourceLine" id="cb238-3" data-line-number="3">                         <span class="dt">importance =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb238-4" data-line-number="4"></a>
<a class="sourceLine" id="cb238-5" data-line-number="5"><span class="co"># el parámetro &quot;importance&quot;: Define si el modelo estimará la importancia relativa de cada predictor en la calidad de la predicción -es decir, cuales variables son más importantes para predecir</span></a>
<a class="sourceLine" id="cb238-6" data-line-number="6"></a>
<a class="sourceLine" id="cb238-7" data-line-number="7"><span class="co"># resultados:</span></a>
<a class="sourceLine" id="cb238-8" data-line-number="8">modelo_RF</a></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = U_S_M2 ~ ., data = entrenamiento, ntree = 500,      importance = TRUE) 
##                Type of random forest: regression
##                      Number of trees: 500
## No. of variables tried at each split: 18
## 
##           Mean of squared residuals: 165967.1
##                     % Var explained: 76.55</code></pre>
<p>Según dice allí, el modelo puede explicar casi el 80% de la varianza de valores encontrada entre los departamentos en venta en 2016 en base a las variables predictoras que empleamos.</p>
<p>¿Qué tiene dentro el modelo?</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1"><span class="kw">summary</span>(modelo_RF)</a></code></pre></div>
<pre><code>##                 Length Class  Mode     
## call               5   -none- call     
## type               1   -none- character
## predicted       4942   -none- numeric  
## mse              500   -none- numeric  
## rsq              500   -none- numeric  
## oob.times       4942   -none- numeric  
## importance       112   -none- numeric  
## importanceSD      56   -none- numeric  
## localImportance    0   -none- NULL     
## proximity          0   -none- NULL     
## ntree              1   -none- numeric  
## mtry               1   -none- numeric  
## forest            11   -none- list     
## coefs              0   -none- NULL     
## y               4942   -none- numeric  
## test               0   -none- NULL     
## inbag              0   -none- NULL     
## terms              3   terms  call</code></pre>
<p>De todo! Por ejemplo, “type” nos emite confirmar qué tipo de análisis realizó: Fue de regresión en este caso, pero podría haber sido otro, como clasificación (cuando se predice un atributo categórico en lugar de una variable continua):</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1">modelo_RF<span class="op">$</span>type</a></code></pre></div>
<pre><code>## [1] &quot;regression&quot;</code></pre>
<p>O “importance”, que contiene un ranking con la importancia relativa de cada predictor, es decir cuáles son los que más ayudan a estimar el valor a predecir:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1">modelo_RF<span class="op">$</span>importance</a></code></pre></div>
<pre><code>##                                %IncMSE IncNodePurity
## M2                      167074.9470156  267184575.80
## M2CUB                   135457.3611587  225668723.10
## AMBIENTES                52277.8971501   64047857.65
## ANTIGUEDAD              182526.0387114  245399435.22
## BAÑOS                    64681.6690831  106473956.16
## M2DESC                  183080.5430261  264761497.03
## DIST_SUBTE              175595.1014987  266112334.80
## LATITUD                 416587.5836090  495386790.77
## LONGITUD                687246.5212418  714824958.86
## BARRIOAGRONOMIA              5.8240775      56815.15
## BARRIOALMAGRO             3519.5707171    5498711.39
## BARRIOBALVANERA           6118.7638268   12871966.47
## BARRIOBARRACAS             570.1771307    1277568.37
## BARRIOBELGRANO           59190.2620500   84952254.92
## BARRIOBOCA                1832.9037306    7775445.23
## BARRIOBOEDO                 97.4133122     734977.42
## BARRIOCABALLITO          23972.4340922   22442509.08
## BARRIOCHACARITA            455.4725383    4795820.89
## BARRIOCOGHLAN              193.2237891     837760.83
## BARRIOCOLEGIALES          1460.8036155    5031914.64
## BARRIOCONSTITUCION        1273.1384772    3288128.96
## BARRIOFLORES               572.0632495    2027860.77
## BARRIOFLORESTA              64.5978362     573233.32
## BARRIOLINIERS              181.6202793     362768.59
## BARRIOMATADEROS            255.6264803     848580.79
## BARRIOMONSERRAT           3694.4926149    6663653.93
## BARRIOMONTE_CASTRO         215.7103189     660037.96
## BARRIONUEVA_POMPEYA          0.6799792     110671.72
## BARRIONUÑEZ               2551.2087561    7163816.75
## BARRIOPALERMO            96786.2217651  141530565.58
## BARRIOPARQUE_AVELLANEDA     -0.1274300      42681.02
## BARRIOPARQUE_CHACABUCO   21888.3230863   24564481.00
## BARRIOPARQUE_CHAS         3409.1373106   13595523.78
## BARRIOPARQUE_PATRICIOS     420.0668951     736718.16
## BARRIOPATERNAL               0.0000000     101935.71
## BARRIOPUERTO_MADERO      64001.6002284  195408094.01
## BARRIORECOLETA           25467.2782861   27510223.58
## BARRIORETIRO              1609.0848122    7530449.82
## BARRIOSAAVEDRA            1099.0982473    2617816.50
## BARRIOSAN_CRISTOBAL      18846.9345260   15214434.45
## BARRIOSAN_NICOLAS         1933.0773150    3204284.32
## BARRIOSAN_TELMO              1.4341777    1507344.99
## BARRIOVELEZ_SARSFIELD       -5.1809270     217132.96
## BARRIOVERSALLES             -1.3455801      29519.37
## BARRIOVILLA_CRESPO       20237.3386725   17192884.91
## BARRIOVILLA_DEL_PARQUE      84.0611189     546234.26
## BARRIOVILLA_DEVOTO          64.7508980    1315630.39
## BARRIOVILLA_GRAL._MITRE     13.8231362     419921.76
## BARRIOVILLA_LUGANO         244.5047965    1978559.22
## BARRIOVILLA_LURO           -27.0631812     627467.87
## BARRIOVILLA_ORTUZAR        285.5320719    1692417.58
## BARRIOVILLA_PUEYRREDON     207.7096264     738130.59
## BARRIOVILLA_REAL             3.7251238      61017.22
## BARRIOVILLA_SANTA_RITA      35.6007291     325280.23
## BARRIOVILLA_SOLDATI        159.9408661    1527550.21
## BARRIOVILLA_URQUIZA       1161.7714972    2254659.78</code></pre>
<p>La columna “%IncMSE” representa el porcentaje de error promedio, la magnitud en la que el valor predicho por el modelo difiere del valor observado, cuando cada predictor se retira del modelo (es decir, cuanto peor sería la predicción si no se usara). Por eso los números mayores están asociados a los predictores de más peso, que en este caso son LONGITUD, LATITUD, M2DESC, ANTIGUEDAD y DIST_SUBTE. Además de encontrar la correlación esperable entre el valor del m2 y la superficie descubierta de las propiedades, los años de antiguedad y la distancia al subte, nuestro modelo ha encontrado que la ubicación (latitud y longitud) es la clave del valor de la propiedad… y sin saber nada de geografía ni urbanismo.</p>
<p>En “predicted” tenemos la mediana del valor del m2 predicho para cada departamento:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1"><span class="kw">head</span>(modelo_RF<span class="op">$</span>predicted)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 2769.821 3375.679 3843.473 2252.623 2150.995 3112.547</code></pre>
<p>Aprovechando que dentro del modelo, “y” contiene los valores observados, evaluemos en forma gráfica cuánto se aproximan las predicciones de cada departamento al valor real (el observado):</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb248-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> modelo_RF<span class="op">$</span>predicted, <span class="dt">y =</span> modelo_RF<span class="op">$</span>y), <span class="dt">alpha =</span> <span class="fl">0.3</span>) </a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-207-1.png" width="672" /></p>
<p>Se ajusta bastante bien. Luego veremos una manera de cuantificar la precisión del modelo.</p>
</div>
<div id="midiendo-la-performance-del-modelo-contra-datos-que-no-conoce" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Midiendo la performance del modelo contra datos que no conoce</h3>
<p>Veamos ahora como se comporta nuestro modelo cuando debe predecir valores de distritos que no se han utilizado para el entrenamiento, los que reservamos para el set de testeo.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" data-line-number="1">predicciones_test &lt;-<span class="st"> </span><span class="kw">predict</span>(modelo_RF, <span class="dt">newdata =</span> testeo)</a>
<a class="sourceLine" id="cb249-2" data-line-number="2"></a>
<a class="sourceLine" id="cb249-3" data-line-number="3"><span class="kw">head</span>(predicciones_test)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 3487.456 2328.357 3805.220 3091.276 3195.991 3039.174</code></pre>
<p>En un gráfico:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb251-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> predicciones_test, <span class="dt">y =</span> testeo<span class="op">$</span>U_S_M2), <span class="dt">alpha =</span> <span class="fl">0.3</span>) </a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-209-1.png" width="672" /></p>
</div>
<div id="comparando-performance" class="section level3">
<h3><span class="header-section-number">7.5.3</span> Comparando performance</h3>
<p>Es práctico obtener un sólo número, un indicador simple que nos diga que tan bien predice el modelo, y así poder comparar distintos modelos entre si (o distintos datasets contra el mismo modelo) utilizando esa medida. En estadística es común el uso del RMSE como indicador de grado de ajuste, o “Root Mean Square Error” - la raíz cuadrada de la media de los errores al cuadrado.</p>
<p>El modelo incluye el MSE (o sea la suma de los errores al cuadrado) que surge de comparar predicciones con valores observados. Y en el caso de un random forest, que intenta muchos árboles distintos, varios MSEs resultantes: 500 en nuestro caso, uno por cada árbol trazado.</p>
<p>Tomamos la media de todos los MSE para obtener un valor general, y luego tomamos la raíz cuadrada para obtener el RMSE:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" data-line-number="1">RMSE &lt;-<span class="st"> </span>modelo_RF<span class="op">$</span>mse <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb252-2" data-line-number="2"><span class="st">    </span><span class="kw">mean</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb252-3" data-line-number="3"><span class="st">    </span><span class="kw">sqrt</span>()</a>
<a class="sourceLine" id="cb252-4" data-line-number="4"></a>
<a class="sourceLine" id="cb252-5" data-line-number="5">RMSE</a></code></pre></div>
<pre><code>## [1] 412.5729</code></pre>
<p>Eso significa que la diferencia promedio entre valor esperado y valor hallado para cada distrito fue de 412.5729162 dólares.</p>
<p>Y en comparación, ¿qué tan bueno resultó el modelo cuando se aplicó a datos que no conocía?</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" data-line-number="1">RMSE_test &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">mean</span>((predicciones_test <span class="op">-</span><span class="st"> </span>testeo<span class="op">$</span>U_S_M2)<span class="op">^</span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb254-2" data-line-number="2"></a>
<a class="sourceLine" id="cb254-3" data-line-number="3">RMSE_test</a></code></pre></div>
<pre><code>## [1] 419.6728</code></pre>
<p>Con un valor medio de error de 419.6728037 dólares, el modelo ha funcionado muy bien con datos desconocidos, incluso mejorando levemente su performance respecto al set de <em>training</em>.</p>
<p>Esto indica que no sufre de “overfitting”, la condición de estar excesivamente ajustado a los datos con los que fue entrenado. Por eso el modelo no pierde precisión cuando lidia con datos nuevos.</p>
<p>Como despedida, volvamos al examen visual. Representamos en un gráfico cada valor predicho y cada valor observado para los datos de entrenamiento:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" data-line-number="1"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb256-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(predicciones_test), <span class="dt">y =</span> predicciones_test), </a>
<a class="sourceLine" id="cb256-3" data-line-number="3">               <span class="dt">color =</span> <span class="st">&quot;salmon&quot;</span>,</a>
<a class="sourceLine" id="cb256-4" data-line-number="4">               <span class="dt">alpha =</span> <span class="fl">.5</span>,</a>
<a class="sourceLine" id="cb256-5" data-line-number="5">               <span class="dt">size =</span> <span class="fl">.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb256-6" data-line-number="6"><span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(testeo), <span class="dt">y =</span> testeo<span class="op">$</span>U_S_M2), </a>
<a class="sourceLine" id="cb256-7" data-line-number="7">               <span class="dt">color =</span> <span class="st">&quot;lightblue&quot;</span>,</a>
<a class="sourceLine" id="cb256-8" data-line-number="8">               <span class="dt">alpha =</span> <span class="fl">.5</span>,</a>
<a class="sourceLine" id="cb256-9" data-line-number="9">               <span class="dt">size =</span> <span class="fl">.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb256-10" data-line-number="10"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;valores predichos&quot;</span>,</a>
<a class="sourceLine" id="cb256-11" data-line-number="11">         <span class="dt">y =</span> <span class="st">&quot;valores observados&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb256-12" data-line-number="12"><span class="st">    </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="analitica_urbana_files/figure-html/unnamed-chunk-212-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analizando-movimiento-el-flujo-de-viajes-urbanos.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["analitica_urbana.pdf", "analitica_urbana.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
